# Generated by Django 4.2.4 on 2023-08-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0004_music_singer"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="musics",
            field=models.ManyToManyField(
                related_name="playlists", to="playlists.music"
            ),
        ),
    ]
